---
title: "ACP"
format: html
---

# Bibliotecas

```{r}
library(openxlsx)
library(dplyr)
library(magrittr)
library(corrplot) # gráfico de correlación
library(stats) # prcomp
library(FactoMineR)
library(factoextra)
```

# Se cargan los datos

```{r}
base_INEC <- openxlsx::read.xlsx('Indicadores demográficos INEC.xlsx')
```

```{r}
anno_inicial <- 1960
anno_final <- 2021

base_INEC %<>% dplyr::filter(anno_inicial <= anno & anno <= anno_final)

# cantidad de NA's por variable: 0
# colSums(is.na(base_INEC)) 
```

```{r}
# Se quita el año de la base (para ser proyectado como variable suplementaria)
base_ACP <- base_INEC %>% select(-anno)
rownames(base_ACP) <- base_INEC$anno
```

```{r}
corrplot(cor(base_ACP))
```
```{r}
summary(base_ACP)
```

# Análisis en componentes principales (normado)

Usamos $\texttt{ACP}$ de $\texttt{FactoMineR}$

```{r}
ACP_INEC <- FactoMineR::PCA(base_ACP, scale.unit = TRUE, 
                            graph = FALSE)
```

```{r}
# factoextra::get_eigenvalue(ACP_INEC)
```


```{r}
factoextra::fviz_eig(ACP_INEC)
```

```{r}
factoextra::fviz_pca_var(ACP_INEC, repel = TRUE)
```
```{r}
factoextra::fviz_pca_ind(ACP_INEC)
```

```{r}
# factoextra::fviz_pca_biplot(ACP_INEC)
```

```{r}
fviz_cos2(ACP_INEC, choice = "ind", axes = 1:2, top = 30)
```
```{r}
fviz_cos2(ACP_INEC, choice = "var", axes = 1:2)
```

```{r}
fviz_contrib(ACP_INEC, choice = "ind", axes = 1:2, top = 30)
```

```{r}
base_ACP_diff  <- base_ACP
base_ACP_diff[, c(1:7, 17:20, 27)] <- log(base_ACP_diff[, c(1:7, 17:20, 27)])
base_ACP_diff <- apply(base_ACP_diff, MARGIN = 2, FUN = diff)


```


```{r}
ACP_INEC_diff <-  FactoMineR::PCA(base_ACP_diff, scale.unit = TRUE, 
                            graph = FALSE)
```

```{r}
summary(ACP_INEC_diff)
```


```{r}
factoextra::fviz_pca_var(ACP_INEC_diff, repel = TRUE)
```

```{r}
factoextra::fviz_pca_ind(ACP_INEC_diff)
```

```{r}
factoextra::fviz_pca_biplot(ACP_INEC_diff)
```

```{r}
factoextra::fviz_eig(ACP_INEC_diff)
```

